# Generated by Django 2.1.2 on 2018-12-16 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Graph',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, verbose_name='username')),
                ('graph_name', models.CharField(max_length=30, verbose_name='graph name')),
                ('json_data', models.TextField(verbose_name='json_data')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='graph',
            unique_together={('username', 'graph_name')},
        ),
    ]
